name       : mupen64plus-qt
version    : 1.14
release    : 1
source     :
    - https://github.com/dh4/mupen64plus-qt/archive/1.14.tar.gz : 467f4e5b75a0f63f23b1c8266746b3e7932b9dc4ee950c42b2bfaf9660e64614
license    : BSD-3-Clause
component  : games.emulator
summary    : Customizable cross-platform launcher for mupen64plus
description: |
    A customizable cross-platform launcher. This was adapted from CEN64-Qt to work with Mupen64Plus.
builddeps  :
    - pkgconfig(Qt5Core)
    - quazip-devel
rundeps    :
    - mupen64plus
setup      : |
    %qmake
build      : |
    %make
install    : |
    install -Dm00755 $workdir/mupen64plus-qt $installdir/usr/bin/mupen64plus-qt
    install -Dm00644 $workdir/resources/mupen64plus-qt.desktop $installdir/usr/share/applications/mupen64plus-qt.desktop
    install -Dm00644 $workdir/resources/images/mupen64plus.png $installdir/usr/share/pixmaps/mupen64plus-qt.png
